-- Seed ~220 additional questions across 5 new question types
-- true_false: 44, spot_the_bug: 44, multi_select: 44, reorder: 44, fill_blank: 45

-- TRUE/FALSE
INSERT INTO questions (language, difficulty, question_type, code_snippet, question_text, options, correct_answer, explanation) VALUES

-- DIFFICULTY 1 (11 questions)

('python', 1, 'true_false',
 'x = "hello"\nx[0] = "H"',
 'This code will raise a TypeError because strings are immutable in Python.',
 '["True", "False"]', '0',
 'Strings in Python are immutable. You cannot assign to individual characters via indexing. This raises a TypeError.'),

('python', 1, 'true_false',
 'x = [1, 2, 3]\ny = x\ny.append(4)\nprint(len(x))',
 'This code prints 4.',
 '["True", "False"]', '0',
 'y = x does not copy the list; both variables reference the same list object. Appending to y also affects x, so len(x) is 4.'),

('python', 1, 'true_false',
 'print(type(3.0) == type(3))',
 'This code prints True.',
 '["True", "False"]', '1',
 'type(3.0) is <class ''float''> and type(3) is <class ''int''>. They are different types, so the comparison returns False.'),

('python', 1, 'true_false',
 'x = 10\nprint(x > 5 and x < 20)',
 'This code prints True.',
 '["True", "False"]', '0',
 '10 > 5 is True and 10 < 20 is True. True and True evaluates to True.'),

('python', 1, 'true_false',
 'print(10 // 3)',
 'This code prints 3.',
 '["True", "False"]', '0',
 'The // operator performs floor division. 10 // 3 equals 3 (the floor of 3.333...).'),

('python', 1, 'true_false',
 'print(bool(""))',
 'This code prints True.',
 '["True", "False"]', '1',
 'An empty string is falsy in Python. bool("") returns False.'),

('python', 1, 'true_false',
 'x = [1, 2, 3]\nprint(x[-1])',
 'This code prints 1.',
 '["True", "False"]', '1',
 'Negative indexing counts from the end. x[-1] returns the last element, which is 3, not 1.'),

('python', 1, 'true_false',
 'x = {"a": 1, "b": 2}\nprint("a" in x)',
 'This code prints True.',
 '["True", "False"]', '0',
 'The "in" operator on a dictionary checks for key membership. "a" is a key in x, so it prints True.'),

('python', 1, 'true_false',
 'print(2 ** 3)',
 'This code prints 6.',
 '["True", "False"]', '1',
 'The ** operator is exponentiation, not multiplication. 2 ** 3 equals 8, not 6.'),

('python', 1, 'true_false',
 'x = (1, 2, 3)\nprint(len(x))',
 'This code prints 3.',
 '["True", "False"]', '0',
 'Tuples support the len() function. The tuple has 3 elements, so len(x) returns 3.'),

('python', 1, 'true_false',
 'x = "Python"\nprint(x[1:4])',
 'This code prints "yth".',
 '["True", "False"]', '0',
 'String slicing x[1:4] extracts characters at indices 1, 2, and 3. "Python"[1:4] is "yth".'),

-- DIFFICULTY 2 (11 questions)

('python', 2, 'true_false',
 E'def f(lst=[]):\n    lst.append(1)\n    return lst\n\nprint(f())\nprint(f())',
 'Both calls to f() return [1].',
 '["True", "False"]', '1',
 'Default mutable arguments are shared across calls. The first call returns [1], but the second call returns [1, 1] because the same list object is reused.'),

('python', 2, 'true_false',
 'a = [1, 2, 3]\nb = [1, 2, 3]\nprint(a is b)',
 'This code prints True.',
 '["True", "False"]', '1',
 '"is" checks identity (same object in memory), not equality. a and b are two separate list objects, so a is b returns False.'),

('python', 2, 'true_false',
 'a = 256\nb = 256\nprint(a is b)',
 'This code prints True in CPython.',
 '["True", "False"]', '0',
 'CPython caches small integers from -5 to 256. Since 256 is within that range, a and b reference the same cached object, so a is b is True.'),

('python', 2, 'true_false',
 'print(0.1 + 0.2 == 0.3)',
 'This code prints True.',
 '["True", "False"]', '1',
 'Due to floating-point representation, 0.1 + 0.2 is 0.30000000000000004, which is not exactly equal to 0.3.'),

('python', 2, 'true_false',
 'x = [1, [2, 3]]\ny = x.copy()\ny[1].append(4)\nprint(x[1])',
 'This code prints [2, 3, 4].',
 '["True", "False"]', '0',
 'list.copy() creates a shallow copy. The nested list is not copied; both x[1] and y[1] reference the same inner list. Appending 4 to y[1] also affects x[1].'),

('python', 2, 'true_false',
 'print(bool([0]))',
 'This code prints False.',
 '["True", "False"]', '1',
 'A non-empty list is truthy regardless of its contents. [0] has one element, so bool([0]) returns True.'),

('python', 2, 'true_false',
 'a, *b, c = [1, 2, 3, 4, 5]\nprint(b)',
 'This code prints [2, 3, 4].',
 '["True", "False"]', '0',
 'The starred expression *b captures all elements between the first (a=1) and last (c=5), so b is [2, 3, 4].'),

('python', 2, 'true_false',
 E'try:\n    x = 1 / 0\nexcept:\n    pass\nprint("done")',
 'This code raises an unhandled ZeroDivisionError.',
 '["True", "False"]', '1',
 'A bare except clause catches all exceptions, including ZeroDivisionError. The exception is silently caught, and "done" is printed.'),

('python', 2, 'true_false',
 'x = {1, 2, 3}\ny = {3, 4, 5}\nprint(x & y)',
 'This code prints {3}.',
 '["True", "False"]', '0',
 'The & operator on sets computes the intersection. The only common element is 3, so x & y returns {3}.'),

('python', 2, 'true_false',
 E'x = "hello"\nprint(x.replace("l", "L", 1))',
 'This code prints "heLLo".',
 '["True", "False"]', '1',
 'The third argument to replace() limits the number of replacements. With count=1, only the first "l" is replaced, producing "heLlo", not "heLLo".'),

('python', 2, 'true_false',
 'print(isinstance(True, int))',
 'This code prints True.',
 '["True", "False"]', '0',
 'In Python, bool is a subclass of int. Therefore, True is an instance of int, and isinstance(True, int) returns True.'),

-- DIFFICULTY 3 (11 questions)

('python', 3, 'true_false',
 E'funcs = [lambda x: x + i for i in range(3)]\nprint(funcs[0](10))',
 'This code prints 10.',
 '["True", "False"]', '1',
 'This is the classic closure-over-loop-variable problem. All lambdas share the same variable i, which has value 2 after the loop. So funcs[0](10) returns 12, not 10.'),

('python', 3, 'true_false',
 E'def gen():\n    yield 1\n    yield 2\n    yield 3\n\ng = gen()\nprint(sum(g))\nprint(sum(g))',
 'Both sum() calls print 6.',
 '["True", "False"]', '1',
 'A generator is exhausted after one full iteration. The first sum(g) returns 6, but the second sum(g) returns 0 because the generator is already exhausted.'),

('python', 3, 'true_false',
 E'def decorator(func):\n    def wrapper(*args):\n        return func(*args) * 2\n    return wrapper\n\n@decorator\ndef add(a, b):\n    return a + b\n\nprint(add(3, 4))',
 'This code prints 14.',
 '["True", "False"]', '0',
 'The decorator wraps add() so the return value is doubled. add(3, 4) computes 3 + 4 = 7, then the wrapper multiplies by 2 to get 14.'),

('python', 3, 'true_false',
 E'x = [1, 2, 3]\nit = iter(x)\nnext(it)\nnext(it)\nprint(next(it))',
 'This code prints 3.',
 '["True", "False"]', '0',
 'Each call to next() advances the iterator by one. After two calls (returning 1, then 2), the third next() returns 3.'),

('python', 3, 'true_false',
 E'print([x for x in range(10) if x % 2 == 0])',
 'This code prints [0, 2, 4, 6, 8, 10].',
 '["True", "False"]', '1',
 'range(10) produces 0 through 9. The value 10 is not included. The correct output is [0, 2, 4, 6, 8].'),

('python', 3, 'true_false',
 E'import sys\na = []\nb = a\nprint(sys.getrefcount(a) > 2)',
 'This code prints True.',
 '["True", "False"]', '0',
 'The object referenced by a has references from: a, b, and the temporary reference passed as argument to getrefcount(). That is 3, which is greater than 2. So it prints True.'),

('python', 3, 'true_false',
 E'class A:\n    pass\n\nclass B(A):\n    pass\n\nprint(issubclass(B, A))\nprint(issubclass(A, B))',
 'Both print statements output True.',
 '["True", "False"]', '1',
 'B is a subclass of A, so issubclass(B, A) is True. But A is not a subclass of B, so issubclass(A, B) is False.'),

('python', 3, 'true_false',
 E'from collections import Counter\nc = Counter("abracadabra")\nprint(c.most_common(1))',
 'This code prints [(''a'', 5)].',
 '["True", "False"]', '0',
 'In "abracadabra", the letter "a" appears 5 times, which is the most frequent. most_common(1) returns a list with one tuple: [(''a'', 5)].'),

('python', 3, 'true_false',
 E'x = {i: i**2 for i in range(5)}\nprint(x[3])',
 'This code prints 6.',
 '["True", "False"]', '1',
 'The dictionary comprehension maps each i to i**2. x[3] is 3**2 = 9, not 6.'),

('python', 3, 'true_false',
 E'if (n := 10) > 5:\n    print(n)',
 'This code prints 10.',
 '["True", "False"]', '0',
 'The walrus operator (:=) assigns 10 to n and returns the value. Since 10 > 5 is True, the body executes and prints 10.'),

('python', 3, 'true_false',
 E'def f():\n    try:\n        return 1\n    finally:\n        return 2\n\nprint(f())',
 'This code prints 1.',
 '["True", "False"]', '1',
 'The finally block always executes, even when a return is in the try block. The return in finally overrides the return in try, so f() returns 2.'),

-- DIFFICULTY 4 (10 questions)

('python', 4, 'true_false',
 E'class Meta(type):\n    def __new__(mcs, name, bases, namespace):\n        namespace["greeting"] = "hello"\n        return super().__new__(mcs, name, bases, namespace)\n\nclass MyClass(metaclass=Meta):\n    pass\n\nprint(MyClass.greeting)',
 'This code prints "hello".',
 '["True", "False"]', '0',
 'The metaclass Meta injects a "greeting" attribute into every class it creates. MyClass is created using Meta, so MyClass.greeting is "hello".'),

('python', 4, 'true_false',
 E'class D:\n    __slots__ = ["x", "y"]\n\nd = D()\nd.z = 3',
 'This code will raise an AttributeError.',
 '["True", "False"]', '0',
 '__slots__ restricts the instance to only the listed attributes. Assigning d.z raises an AttributeError because "z" is not in __slots__.'),

('python', 4, 'true_false',
 E'class A:\n    def method(self):\n        return "A"\n\nclass B(A):\n    def method(self):\n        return "B"\n\nclass C(A):\n    def method(self):\n        return "C"\n\nclass D(B, C):\n    pass\n\nprint(D().method())',
 'This code prints "C".',
 '["True", "False"]', '1',
 'Python''s MRO (Method Resolution Order) uses C3 linearization. For D(B, C), the MRO is D -> B -> C -> A. So D().method() finds B.method() first and prints "B".'),

('python', 4, 'true_false',
 E'class Desc:\n    def __get__(self, obj, objtype=None):\n        return 42\n\nclass MyClass:\n    val = Desc()\n\nprint(MyClass().val)',
 'This code prints 42.',
 '["True", "False"]', '0',
 'Desc is a data descriptor (well, a non-data descriptor with __get__). When val is accessed on an instance, __get__ is called, returning 42.'),

('python', 4, 'true_false',
 E'import weakref\n\nclass Obj:\n    pass\n\na = Obj()\nw = weakref.ref(a)\ndel a\nprint(w() is None)',
 'This code prints True.',
 '["True", "False"]', '0',
 'After del a, if no other strong references exist, the object is garbage collected. The weak reference w() then returns None, so w() is None is True.'),

('python', 4, 'true_false',
 E'class A:\n    __slots__ = ["x"]\n\nclass B(A):\n    pass\n\nb = B()\nb.y = 10\nprint(b.y)',
 'This code raises an AttributeError.',
 '["True", "False"]', '1',
 'Class B does not define __slots__, so it gets a __dict__ by default. Even though A uses __slots__, B instances can have arbitrary attributes. b.y = 10 works fine and prints 10.'),

('python', 4, 'true_false',
 E'from abc import ABC, abstractmethod\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n\ns = Shape()',
 'This code raises a TypeError because you cannot instantiate an abstract class.',
 '["True", "False"]', '0',
 'A class with unimplemented abstract methods cannot be instantiated. Attempting Shape() raises TypeError: Can''t instantiate abstract class Shape with abstract method area.'),

('python', 4, 'true_false',
 E'class MyClass:\n    def __init_subclass__(cls, **kwargs):\n        super().__init_subclass__(**kwargs)\n        cls.registry = True\n\nclass Child(MyClass):\n    pass\n\nprint(Child.registry)',
 'This code prints True.',
 '["True", "False"]', '0',
 '__init_subclass__ is called on the parent class when a subclass is defined. It sets registry = True on the Child class, so Child.registry is True.'),

('python', 4, 'true_false',
 E'import sys\na = "hello"\nb = "hello"\nprint(a is b)',
 'This result is guaranteed by the Python language specification.',
 '["True", "False"]', '1',
 'While CPython interns short string literals (so a is b may return True), this is an implementation detail, not guaranteed by the language specification. Other implementations may behave differently.'),

('python', 4, 'true_false',
 E'class Frozen:\n    __slots__ = ()\n\nf = Frozen()\nf.x = 1',
 'This code raises an AttributeError.',
 '["True", "False"]', '0',
 'An empty __slots__ = () means no instance attributes are allowed and no __dict__ is created. Attempting to set f.x raises an AttributeError.'),

('python', 4, 'true_false',
 E'class Counter:\n    count = 0\n    def __init__(self):\n        Counter.count += 1\n\na = Counter()\nb = Counter()\nprint(a.count == b.count == 2)',
 'This code prints True.',
 '["True", "False"]', '0',
 'count is a class variable shared by all instances. Each __init__ increments Counter.count. After two instances, Counter.count is 2. Both a.count and b.count resolve to the class variable, which is 2, so the comparison is True.');

-- SPOT THE BUG
INSERT INTO questions (language, difficulty, question_type, code_snippet, question_text, options, correct_answer, explanation) VALUES

-- ==================== DIFFICULTY 1 (11 questions) ====================

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def is_even(n):", "    if n % 2 = 0:", "        return True", "    return False"]',
 '1',
 'Uses assignment operator `=` instead of comparison operator `==`. Should be `if n % 2 == 0:`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def add(a, b):", "    result = a + b", "    return reuslt", ""]',
 '2',
 'Typo in variable name: `reuslt` should be `result`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def square(n):", "    return n * 2", "", "print(square(5))"]',
 '1',
 'Uses `n * 2` (multiplication by 2) instead of `n ** 2` (exponentiation). This doubles the number instead of squaring it.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["name = ''hello world''", "upper_name = name.upper()", "first_word = name.splat('' '')[0]", "print(first_word)"]',
 '2',
 'Wrong string method: `splat` does not exist. Should be `split`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def say_hello(name)", "    greeting = f''Hello, {name}!''", "    print(greeting)", "    return greeting"]',
 '0',
 'Missing colon at the end of the function definition. Should be `def say_hello(name):`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["numbers = [1, 2, 3, 4, 5]", "total = sum(numbers)", "average = total / len(number)", "print(average)"]',
 '2',
 'Typo in variable name: `number` should be `numbers`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def get_length(text):", "    count = lan(text)", "    return count", "print(get_length(''hello''))"]',
 '1',
 'Wrong function call: `lan` does not exist. Should be `len`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["fruits = [''apple'', ''banana'', ''cherry'']", "last = fruits[-1]", "first = fruits[1]", "print(first, last)"]',
 '2',
 'Wrong index: `fruits[1]` returns ''banana'', not the first element. The first element is at index 0.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def is_positive(n):", "    if n >= 0:", "        return True", "    return False"]',
 '1',
 'Wrong comparison operator: `>=` includes zero, but zero is not positive. Should be `n > 0`.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["word = ''Python''", "lowered = word.Lower()", "print(lowered)", ""]',
 '1',
 'Python is case-sensitive: `Lower()` does not exist. Should be `lower()` with a lowercase L.'),

('python', 1, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def max_of_three(a, b, c):", "    if a > b and a > c:", "        return a", "    if b > c:", "        return b", "    return a"]',
 '5',
 'When c is the largest, the function incorrectly returns `a`. The last line should be `return c`.'),

-- ==================== DIFFICULTY 2 (11 questions) ====================

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def first_n(lst, n):", "    result = []", "    for i in range(1, n):", "        result.append(lst[i])", "    return result"]',
 '2',
 'Off-by-one: `range(1, n)` starts at index 1 and misses index 0. Should be `range(n)` to get the first n elements.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def find_min_max(numbers):", "    min_val = min(numbers)", "    max_val = max(numbers)", "    return min_val, min_val"]',
 '3',
 'Wrong variable in return: returns `min_val` twice instead of `min_val, max_val`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def remove_evens(numbers):", "    for n in numbers:", "        if n % 2 == 0:", "            numbers.remove(n)", "    return numbers"]',
 '1',
 'Modifying a list while iterating over it causes elements to be skipped. Should iterate over a copy: `for n in numbers[:]:`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def average(a, b):", "    total = a + b", "    return total // 2", "print(average(3, 4))"]',
 '2',
 'Integer division `//` truncates the result. `average(3, 4)` returns 3 instead of 3.5. Should use `/` for true division.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def safe_divide(a, b):", "    try:", "        return a / b", "    except ValueError:", "        return None"]',
 '3',
 'Wrong exception type: division by zero raises `ZeroDivisionError`, not `ValueError`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def count_down(n):", "    numbers = []", "    for i in range(n, 0):", "        numbers.append(i)", "    return numbers"]',
 '2',
 'Missing step argument: `range(n, 0)` produces an empty sequence when n > 0. Should be `range(n, 0, -1)`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def flatten(nested):", "    result = []", "    for sublist in nested:", "        result.append(sublist)", "    return result"]',
 '3',
 'Using `append` adds each sublist as a single element. Should use `result.extend(sublist)` to flatten.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def get_keys_and_vals(d):", "    keys = list(d.keys())", "    vals = list(d.keys())", "    return keys, vals"]',
 '2',
 'Copy-paste bug: calls `d.keys()` twice. The second call should be `d.values()`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def reverse_string(s):", "    chars = list(s)", "    chars.reverse()", "    return chars"]',
 '3',
 'Returns a list of characters instead of a string. Should be `return ''''.join(chars)`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["data = {''a'': 1, ''b'': 2}", "for key in data:", "    data[key + ''_new''] = data[key]", "print(data)"]',
 '2',
 'Modifying a dictionary while iterating over it raises a RuntimeError. Should iterate over a copy: `for key in list(data):`.'),

('python', 2, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def factorial(n):", "    if n == 0:", "        return 0", "    return n * factorial(n - 1)"]',
 '2',
 'Base case returns 0 instead of 1. Since everything gets multiplied by 0, `factorial(n)` always returns 0. Should be `return 1`.'),

-- ==================== DIFFICULTY 3 (11 questions) ====================

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def make_funcs():", "    funcs = []", "    for i in range(5):", "        funcs.append(lambda: i)", "    return funcs"]',
 '3',
 'Closure variable capture in loop: all lambdas share the same variable `i` and will all return 4. Fix with `lambda i=i: i` to capture current value.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def add_item(item, lst=[]):", "    lst.append(item)", "    return lst", ""]',
 '0',
 'Mutable default argument: the default list `[]` is shared across all calls, accumulating items. Should use `lst=None` and create a new list inside the function.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Animal:", "    def __init__(self, name):", "        self.name = name", "", "class Dog(Animal):", "    def __init__(self, name, breed):", "        self.breed = breed"]',
 '6',
 'Missing `super().__init__(name)` call. The Dog class never initializes `self.name` from the parent Animal class.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class MyClass:", "    count = 0", "    @staticmethod", "    def increment(self):", "        MyClass.count += 1"]',
 '3',
 'A `@staticmethod` does not receive `self`. Having `self` as a parameter means the first argument passed will be assigned to `self` instead of being the instance. Remove `self` or use a regular method.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def process_large(data):", "    result = (x ** 2 for x in data)", "    total = sum(result)", "    avg = sum(result) / len(data)"]',
 '3',
 'Generator exhaustion: `result` is a generator consumed by the first `sum()`. The second `sum(result)` returns 0, making avg always 0. Convert to list first or compute in one pass.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["import copy", "original = [[1, 2], [3, 4]]", "cloned = copy.copy(original)", "cloned[0].append(5)", "print(original)"]',
 '2',
 'Shallow copy with `copy.copy()` only copies the outer list. Inner lists are still shared references, so modifying `cloned[0]` also modifies `original[0]`. Use `copy.deepcopy()`.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Counter:", "    def __init__(self):", "        self.count = 0", "    def __call__(self):", "        self.count += 1", "    def __str__(self):", "        return self.count"]',
 '6',
 '`__str__` must return a string, but it returns an integer (`self.count`). This raises TypeError. Should be `return str(self.count)`.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Singleton:", "    _instance = None", "    def __new__(cls):", "        if cls._instance is None:", "            cls._instance = object().__new__(cls)", "        return cls._instance"]',
 '4',
 'Incorrect call: `object().__new__(cls)` calls `__new__` on an object *instance*. Should be `object.__new__(cls)` (calling on the class, not an instance) or `super().__new__(cls)`.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["def apply_discount(prices, pct):", "    return {k: v * 1 - pct / 100", "           for k, v in prices.items()}", ""]',
 '1',
 'Operator precedence: `v * 1 - pct / 100` evaluates as `(v * 1) - (pct / 100)`. Missing parentheses: should be `v * (1 - pct / 100)`.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Node:", "    def __init__(self, val, children=[]):", "        self.val = val", "        self.children = children"]',
 '1',
 'Mutable default argument in `__init__`: all Node instances created without explicit children share the same list object. Appending to one node''s children affects all others. Use `children=None`.'),

('python', 3, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Temperature:", "    def __init__(self, c):", "        self.celsius = c", "    @property", "    def fahrenheit(self):", "        return self.celsius * 9 / 5 + 32", "    @fahrenheit.setter", "    def fahrenheit(self, value):", "        self.celsius = value"]',
 '8',
 'The setter assigns the Fahrenheit value directly to celsius without converting. Should be `self.celsius = (value - 32) * 5 / 9`.'),

-- ==================== DIFFICULTY 4 (11 questions) ====================

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Point:", "    def __init__(self, x, y):", "        self.x, self.y = x, y", "    def __eq__(self, other):", "        return self.x == other.x and self.y == other.y"]',
 '3',
 'Defining `__eq__` without `__hash__` makes Point instances unhashable. Python sets `__hash__` to None when `__eq__` is overridden, so Points can no longer be used in sets or as dict keys.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class A:", "    def greet(self): return ''A''", "class B(A):", "    def greet(self): return ''B''", "class C(A):", "    def greet(self): return ''C''", "class D(B, C):", "    def greet(self): return super(B, self).greet()"]',
 '7',
 'Wrong MRO super call: `super(B, self)` skips B and resumes at C (the next class in D''s MRO: D->B->C->A). If the intent is to call A.greet, it incorrectly calls C.greet instead.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["async def producer(queue):", "    for i in range(10):", "        queue.put(i)", "    await queue.put(None)"]',
 '2',
 'Missing `await` on `queue.put(i)`. `asyncio.Queue.put()` is a coroutine that must be awaited. Without await, the item is never actually placed in the queue and the coroutine is silently discarded.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Validator:", "    def __init_subclass__(cls, **kwargs):", "        super().__init_subclass__(**kwargs)", "        if not hasattr(cls, ''validate''):", "            raise TypeError(f''{cls} needs validate'')"]',
 '3',
 '`hasattr` traverses the MRO, so a parent''s `validate` method satisfies the check. Subclasses that don''t define their own `validate` won''t raise an error. Should check `''validate'' in cls.__dict__`.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class CachedProp:", "    def __init__(self, func):", "        self.func = func", "    def __get__(self, obj, cls):", "        val = self.func(obj)", "        setattr(obj, self.func.__name__, val)", "        return val"]',
 '4',
 'When accessed on the class itself (e.g., `MyClass.prop`), `obj` is None, so `self.func(None)` is called, causing an error. Should check `if obj is None: return self` before computing the value.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Meta(type):", "    def __new__(mcs, name, bases, ns):", "        cls = super().__new__(mcs, name, bases, ns)", "        return cls", "    def __init__(cls, name, bases, ns):", "        cls.registry = []", "        super().__init__(name, bases, ns)"]',
 '5',
 'Setting `cls.registry = []` in metaclass `__init__` resets the registry to an empty list for every class created, including subclasses. Subclasses lose any items registered by the parent. Should append to an existing registry or only initialize if not present.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["from weakref import WeakValueDictionary", "class Cache:", "    def __init__(self):", "        self._store = WeakValueDictionary()", "    def put(self, key, value):", "        self._store[key] = value"]',
 '5',
 'WeakValueDictionary holds weak references. If no other strong reference to `value` exists, it is garbage collected immediately and disappears from the cache. This is unreliable for caching values that aren''t held elsewhere.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class Immutable:", "    __slots__ = (''x'', ''y'')", "    def __init__(self, x, y):", "        self.x = x", "        self.y = y", "    def __setattr__(self, key, val):", "        raise AttributeError(''Immutable!'')"]',
 '5',
 '`__setattr__` intercepts ALL attribute assignments, including those in `__init__`. Setting `self.x = x` and `self.y = y` will raise AttributeError. Must use `object.__setattr__(self, key, val)` inside `__init__`.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["import contextlib", "@contextlib.contextmanager", "def managed(name):", "    res = acquire(name)", "    yield res", "    release(res)"]',
 '4',
 'If code inside the `with` block raises an exception, `release(res)` never executes. The yield must be wrapped in try/finally: `try: yield res` / `finally: release(res)` to guarantee cleanup.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["class TypedAttr:", "    def __set_name__(self, owner, name):", "        self.name = name", "    def __set__(self, obj, value):", "        obj.__dict__[self.name] = value", "    def __get__(self, obj, cls):", "        return obj.__dict__[self.name]"]',
 '6',
 'When accessed on the class (e.g., `MyClass.attr`), `obj` is None, so `None.__dict__` raises AttributeError. The `__get__` method should check `if obj is None: return self`.'),

('python', 4, 'spot_the_bug',
 '',
 'Which line contains the bug?',
 '["async def timeout_fetch(url):", "    try:", "        async with aiohttp.ClientSession() as s:", "            resp = await s.get(url, timeout=5)", "            return await resp.json()", "    except asyncio.TimeoutError:", "        return None"]',
 '3',
 'Passing `timeout=5` as an integer is incorrect for aiohttp. It requires an `aiohttp.ClientTimeout` object: `timeout=aiohttp.ClientTimeout(total=5)`. An integer is silently ignored or raises TypeError depending on the version.');

-- MULTI-SELECT
INSERT INTO questions (language, difficulty, question_type, code_snippet, question_text, options, correct_answer, explanation) VALUES

-- DIFFICULTY 1 (11 questions)

('python', 1, 'multi_select',
 '',
 'Which of the following are valid built-in data types in Python?',
 '["list", "array", "dict", "tuple", "hashtable"]',
 '[0, 2, 3]',
 'list, dict, and tuple are built-in Python types. array requires importing the array module, and hashtable is not a Python type (dict serves that role).'),

('python', 1, 'multi_select',
 '',
 'Which of the following are Python keywords?',
 '["for", "while", "loop", "elif", "switch"]',
 '[0, 1, 3]',
 'for, while, and elif are Python keywords. loop and switch do not exist as keywords in Python (Python uses match/case instead of switch, added in 3.10).'),

('python', 1, 'multi_select',
 '',
 'Which of the following are mutable data types in Python?',
 '["list", "tuple", "dict", "set", "str"]',
 '[0, 2, 3]',
 'list, dict, and set are mutable — their contents can be changed after creation. tuple and str are immutable.'),

('python', 1, 'multi_select',
 '',
 'Which of the following are valid ways to create an empty list in Python?',
 '["[]", "list()", "new list()", "list.new()"]',
 '[0, 1]',
 '[] and list() both create an empty list. Python does not use new keyword syntax or a .new() constructor method.'),

('python', 1, 'multi_select',
 '',
 'Which of the following are valid Python string methods?',
 '["upper()", "lower()", "trim()", "strip()", "length()"]',
 '[0, 1, 3]',
 'upper(), lower(), and strip() are valid string methods. Python uses strip() instead of trim(), and len() is a built-in function, not a string method.'),

('python', 1, 'multi_select',
 '',
 'Which of the following statements about Python lists are true?',
 '["Lists are ordered", "Lists can contain mixed types", "Lists are immutable", "Lists support indexing"]',
 '[0, 1, 3]',
 'Lists are ordered, can contain elements of different types, and support indexing. Lists are mutable, not immutable.'),

('python', 1, 'multi_select',
 '',
 'Which of the following are valid comparison operators in Python?',
 '["==", "!=", "===", "is", "<>"]',
 '[0, 1, 3]',
 '==, !=, and is are valid Python operators. === does not exist in Python (that is JavaScript). <> was removed in Python 3.'),

('python', 1, 'multi_select',
 '',
 'Which of the following are valid boolean values or expressions that evaluate to True in Python?',
 '["True", "1", "0", "\"hello\""]',
 '[0, 1, 3]',
 'True, 1, and non-empty strings like "hello" are all truthy. 0 is falsy in Python.'),

('python', 1, 'multi_select',
 '',
 'Which of the following can be used to define a function in Python?',
 '["def", "lambda", "function", "fn"]',
 '[0, 1]',
 'def defines a named function, and lambda defines an anonymous function. function and fn are not Python keywords.'),

('python', 1, 'multi_select',
 '',
 'Which of the following are immutable types in Python?',
 '["int", "float", "list", "tuple", "str"]',
 '[0, 1, 3, 4]',
 'int, float, tuple, and str are all immutable. list is the only mutable type in this group.'),

('python', 1, 'multi_select',
 '',
 'Which of the following are valid ways to add an element to a list?',
 '["append()", "push()", "insert()", "extend()", "add()"]',
 '[0, 2, 3]',
 'append(), insert(), and extend() are valid list methods. push() does not exist on Python lists (it exists in JavaScript). add() is a set method, not a list method.'),

-- DIFFICULTY 2 (11 questions)

('python', 2, 'multi_select',
 '',
 'Which of the following values are falsy in Python?',
 '["0", "\"\"", "None", "[]", "\"0\""]',
 '[0, 1, 2, 3]',
 '0, empty string "", None, and empty list [] are all falsy. The string "0" is truthy because it is a non-empty string.'),

('python', 2, 'multi_select',
 '',
 'Which of the following list methods modify the list in-place and return None?',
 '["sort()", "sorted()", "reverse()", "append()", "pop()"]',
 '[0, 2, 3]',
 'sort(), reverse(), and append() modify the list in-place and return None. sorted() returns a new list. pop() modifies in-place but returns the removed element.'),

('python', 2, 'multi_select',
 '',
 'Which of the following operations will raise a TypeError?',
 '["\"hello\" + 5", "\"hello\" * 3", "[1, 2] + \"a\"", "len(42)", "3 + 4.5"]',
 '[0, 2, 3]',
 'Concatenating a string with an int, adding a list to a string, and calling len() on an int all raise TypeError. String repetition with * and adding int to float work fine.'),

('python', 2, 'multi_select',
 'x = [1, 2, 3]\ny = x\ny.append(4)',
 'Which statements are true after this code runs?',
 '["x is [1, 2, 3, 4]", "y is [1, 2, 3, 4]", "x is y", "x == y"]',
 '[0, 1, 2, 3]',
 'y = x makes both variables reference the same list object. Appending to y also changes x. They are the same object (x is y) and have equal values (x == y).'),

('python', 2, 'multi_select',
 '',
 'Which of the following string methods return a new string without modifying the original?',
 '["replace()", "upper()", "split()", "strip()", "join()"]',
 '[0, 1, 3, 4]',
 'replace(), upper(), strip(), and join() all return new strings. Strings are immutable so nothing modifies them. split() returns a list, not a string.'),

('python', 2, 'multi_select',
 '',
 'Which of the following can be used as dictionary keys in Python?',
 '["tuple", "string", "int", "list", "frozenset"]',
 '[0, 1, 2, 4]',
 'Dictionary keys must be hashable. tuple (if contents are hashable), string, int, and frozenset are hashable. list is mutable and therefore not hashable.'),

('python', 2, 'multi_select',
 'def f(a, b=[], c=None):\n    pass',
 'Which statements about this function definition are true?',
 '["a is a required argument", "b defaults to a new empty list each call", "c defaults to None", "Using a mutable default argument is a common pitfall"]',
 '[0, 2, 3]',
 'a is required, c defaults to None. The mutable default b=[] is a well-known pitfall because the same list object is reused across calls — it is NOT a new list each call.'),

('python', 2, 'multi_select',
 '',
 'Which of the following are valid set operations in Python?',
 '["union()", "intersection()", "difference()", "append()", "symmetric_difference()"]',
 '[0, 1, 2, 4]',
 'union(), intersection(), difference(), and symmetric_difference() are all valid set methods. append() is a list method; sets use add() instead.'),

('python', 2, 'multi_select',
 'try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print("A")\nexcept Exception:\n    print("B")\nfinally:\n    print("C")',
 'Which strings will be printed?',
 '["A", "B", "C", "No output"]',
 '[0, 2]',
 'ZeroDivisionError is caught by the first except block, printing "A". The finally block always runs, printing "C". The second except is skipped because the exception was already caught.'),

('python', 2, 'multi_select',
 '',
 'Which of the following statements about Python''s range() are true?',
 '["range(5) produces 0 through 4", "range() returns a list", "range(1, 10, 2) produces odd numbers 1 through 9", "range objects are iterable"]',
 '[0, 2, 3]',
 'range(5) gives 0-4, range(1,10,2) gives 1,3,5,7,9, and range objects are iterable. In Python 3, range() returns a range object, not a list.'),

('python', 2, 'multi_select',
 'a = [1, 2, 3]\nb = a[:]\nb.append(4)',
 'Which statements are true after this code runs?',
 '["a == [1, 2, 3]", "b == [1, 2, 3, 4]", "a is b", "len(a) != len(b)"]',
 '[0, 1, 3]',
 'a[:] creates a shallow copy, so b is a different object. Appending to b does not affect a. a remains [1,2,3], b becomes [1,2,3,4], and their lengths differ.'),

-- DIFFICULTY 3 (11 questions)

('python', 3, 'multi_select',
 '',
 'Which of the following statements about Python generators are true?',
 '["They use the yield keyword", "They store all values in memory at once", "They implement the iterator protocol", "They can be iterated only once"]',
 '[0, 2, 3]',
 'Generators use yield, implement the iterator protocol (__iter__ and __next__), and are exhausted after one complete iteration. They produce values lazily, NOT storing all values in memory.'),

('python', 3, 'multi_select',
 '',
 'Which of the following are true about Python decorators?',
 '["They are applied using the @ syntax", "They take a function as an argument", "They must return a function", "They can be stacked on a single function"]',
 '[0, 1, 3]',
 'Decorators use @ syntax, receive a function as an argument, and can be stacked. They do not have to return a function — they can return any callable object or even a non-callable (though that would make the name no longer callable).'),

('python', 3, 'multi_select',
 '',
 'Which of the following are part of the iterator protocol in Python?',
 '["__iter__", "__next__", "__getitem__", "__len__", "__enter__"]',
 '[0, 1]',
 'The iterator protocol requires __iter__ (return the iterator) and __next__ (return the next value). __getitem__ enables indexing, __len__ returns length, and __enter__ is for context managers.'),

('python', 3, 'multi_select',
 'from contextlib import contextmanager\n\n@contextmanager\ndef my_ctx():\n    print("enter")\n    yield 42\n    print("exit")',
 'Which statements about this context manager are true?',
 '["Code before yield runs on __enter__", "Code after yield runs on __exit__", "The yielded value is bound by as", "The function can yield multiple times"]',
 '[0, 1, 2]',
 'In a @contextmanager, code before yield runs on entry, code after on exit, and the yielded value is available via as. The function must yield exactly once.'),

('python', 3, 'multi_select',
 '',
 'Which of the following statements about Python closures are true?',
 '["A closure captures variables from the enclosing scope", "Captured variables are evaluated at definition time", "The nonlocal keyword allows modifying enclosed variables", "Closures can access but not rebind enclosed variables without nonlocal"]',
 '[0, 2, 3]',
 'Closures capture variables from enclosing scopes. Captured variables use late binding (evaluated at call time, not definition time). nonlocal is needed to rebind enclosed variables.'),

('python', 3, 'multi_select',
 'class A:\n    def method(self):\n        return "A"\n\nclass B(A):\n    pass\n\nclass C(A):\n    def method(self):\n        return "C"\n\nclass D(B, C):\n    pass',
 'Which statements about D().method() are true?',
 '["It returns \"C\"", "Python uses C3 linearization for MRO", "The MRO of D is D -> B -> C -> A", "B.method is called"]',
 '[0, 1, 2]',
 'Python''s C3 linearization gives MRO: D -> B -> C -> A -> object. B has no method override, so C.method is found next, returning "C". B.method is not called directly.'),

('python', 3, 'multi_select',
 '',
 'Which of the following statements about Python''s *args and **kwargs are true?',
 '["*args collects positional arguments as a tuple", "**kwargs collects keyword arguments as a dict", "*args must come before **kwargs in a function signature", "You can use * and ** to unpack when calling a function"]',
 '[0, 1, 2, 3]',
 'All four statements are correct. *args gathers positional args as a tuple, **kwargs gathers keyword args as a dict, *args must precede **kwargs, and * / ** can unpack iterables/dicts in calls.'),

('python', 3, 'multi_select',
 '',
 'Which statements about Python''s Global Interpreter Lock (GIL) are true?',
 '["It prevents multiple threads from executing Python bytecode simultaneously", "It affects CPU-bound multithreaded programs", "It is released during I/O operations", "It exists in all Python implementations"]',
 '[0, 1, 2]',
 'The GIL prevents concurrent Python bytecode execution, hurts CPU-bound threading, and is released during I/O. It is specific to CPython — Jython and IronPython do not have a GIL.'),

('python', 3, 'multi_select',
 'def make_funcs():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda: i)\n    return funcs',
 'Which statements about make_funcs() are true?',
 '["All three lambdas return 2", "Each lambda captures the variable i by reference", "Using lambda i=i: i would fix the issue", "This demonstrates late binding in closures"]',
 '[0, 1, 2, 3]',
 'All lambdas share the same reference to i, which is 2 after the loop. This is late binding. Using a default argument (i=i) captures the current value at each iteration, fixing the issue.'),

('python', 3, 'multi_select',
 '',
 'Which of the following are true about Python''s __slots__?',
 '["It restricts the attributes an instance can have", "It can reduce memory usage", "It prevents creation of __dict__ on instances", "Subclasses automatically inherit the slot restriction"]',
 '[0, 1, 2]',
 '__slots__ restricts allowed attributes, reduces memory by avoiding per-instance __dict__, and prevents __dict__ creation. Subclasses do NOT automatically inherit the restriction — they need their own __slots__.'),

('python', 3, 'multi_select',
 '',
 'Which of the following statements about Python list comprehensions are true?',
 '["They can include conditional filtering", "They create a new list object", "Variables leak into the enclosing scope in Python 3", "They can be nested"]',
 '[0, 1, 3]',
 'List comprehensions support conditions, create new lists, and can be nested. In Python 3, the loop variable does NOT leak into the enclosing scope (this was fixed from Python 2).'),

-- DIFFICULTY 4 (11 questions)

('python', 4, 'multi_select',
 '',
 'Which of the following statements about Python descriptors are true?',
 '["A descriptor implements __get__, __set__, or __delete__", "Data descriptors have priority over instance __dict__", "Non-data descriptors only implement __get__", "Descriptors must be defined on the class, not the instance"]',
 '[0, 1, 2, 3]',
 'All are true. Descriptors implement one or more of __get__/__set__/__delete__. Data descriptors (with __set__ or __delete__) take priority over instance __dict__. Non-data descriptors only define __get__. Descriptors must live on the class.'),

('python', 4, 'multi_select',
 '',
 'Which statements about Python metaclasses are true?',
 '["type is the default metaclass", "Metaclasses control class creation", "__init_subclass__ can be an alternative to metaclasses", "A metaclass must inherit from type"]',
 '[0, 1, 2]',
 'type is the default metaclass, and metaclasses control class creation. __init_subclass__ (added in Python 3.6) can replace some metaclass use cases. A metaclass does not strictly have to inherit from type — any callable that returns a class works.'),

('python', 4, 'multi_select',
 '',
 'Which of the following statements about Python''s garbage collection are true?',
 '["CPython primarily uses reference counting", "The gc module handles cyclic references", "Objects with __del__ can cause issues with cycle collection", "Weak references prevent reference count increases"]',
 '[0, 1, 2, 3]',
 'All are true. CPython uses reference counting as primary GC. The gc module detects cycles. Objects with __del__ finalizers can complicate cycle collection. Weak references (weakref) do not increment the reference count.'),

('python', 4, 'multi_select',
 'class Meta(type):\n    def __new__(mcs, name, bases, namespace):\n        namespace[''greeting''] = ''hello''\n        return super().__new__(mcs, name, bases, namespace)\n\nclass MyClass(metaclass=Meta):\n    pass',
 'Which statements about this code are true?',
 '["MyClass.greeting equals \"hello\"", "Meta.__new__ runs when MyClass is defined", "MyClass() will have a greeting attribute", "Meta is an instance of type"]',
 '[0, 1, 2, 3]',
 'The metaclass __new__ runs at class definition time and injects greeting into the namespace. MyClass.greeting is "hello", instances inherit it, and Meta inherits from type so it is also an instance of type.'),

('python', 4, 'multi_select',
 '',
 'Which statements about Python''s import system are true?',
 '["Modules are cached in sys.modules", "Circular imports always raise ImportError", "__init__.py makes a directory a regular package", "importlib can be used to dynamically import modules"]',
 '[0, 2, 3]',
 'Modules are cached in sys.modules. __init__.py defines regular packages. importlib supports dynamic imports. Circular imports do NOT always raise ImportError — they often work partially, only failing if a name is accessed before it is defined.'),

('python', 4, 'multi_select',
 '',
 'Which of the following statements about Python''s async/await are true?',
 '["await can only be used inside async functions", "asyncio.run() starts the event loop", "async generators use yield inside async def", "Multiple coroutines run on separate OS threads by default"]',
 '[0, 1, 2]',
 'await requires async context, asyncio.run() starts the event loop, and async generators use yield in async def. Coroutines run concurrently on a single thread via the event loop, NOT on separate OS threads.'),

('python', 4, 'multi_select',
 '',
 'Which statements about Python''s data model and attribute lookup are true?',
 '["Data descriptors take priority over instance variables", "Instance __dict__ takes priority over non-data descriptors", "__getattr__ is called only when normal lookup fails", "__getattribute__ is called for every attribute access"]',
 '[0, 1, 2, 3]',
 'All are true. The lookup order is: data descriptors > instance __dict__ > non-data descriptors / class variables. __getattribute__ is called on every access. __getattr__ is the fallback when normal lookup fails.'),

('python', 4, 'multi_select',
 '',
 'Which of the following are true about Python''s memory model for integers?',
 '["CPython caches small integers (-5 to 256)", "Integer objects are immutable", "is comparison on large integers is unreliable", "Python integers have arbitrary precision"]',
 '[0, 1, 2, 3]',
 'CPython interns small integers from -5 to 256. All integers are immutable. Using is on large integers is unreliable because separate objects may be created. Python ints have unlimited precision.'),

('python', 4, 'multi_select',
 'class A:\n    def __init_subclass__(cls, **kwargs):\n        super().__init_subclass__(**kwargs)\n        cls.registry = True\n\nclass B(A):\n    pass\n\nclass C(B):\n    pass',
 'Which statements about this code are true?',
 '["B.registry is True", "C.registry is True", "__init_subclass__ is called for indirect subclasses", "A.registry exists"]',
 '[0, 1, 2]',
 '__init_subclass__ is called when B and C are defined (both are subclasses of A, directly or indirectly). B.registry and C.registry are both True. A itself does not trigger __init_subclass__ on itself, so A.registry does not exist.'),

('python', 4, 'multi_select',
 '',
 'Which statements about Python''s ABC (Abstract Base Class) module are true?',
 '["@abstractmethod prevents instantiation of the class directly", "ABCs can define concrete methods alongside abstract ones", "register() can make a class a virtual subclass without inheritance", "Abstract classes must inherit from ABC or use ABCMeta"]',
 '[0, 1, 2, 3]',
 'All are true. @abstractmethod makes a class uninstantiable until all abstract methods are overridden. ABCs can mix abstract and concrete methods. register() creates virtual subclasses. Abstract classes require ABC or ABCMeta.'),

('python', 4, 'multi_select',
 '',
 'Which of the following are true about Python''s __prepare__ method in metaclasses?',
 '["It controls the namespace object used during class body execution", "It must return a mapping object", "It is called before the class body is executed", "It can be used to implement ordered class attributes"]',
 '[0, 1, 2, 3]',
 'All are true. __prepare__ returns the namespace mapping used during class body execution. It is called before the body runs. By returning an OrderedDict (pre-3.7) or custom mapping, it can track attribute definition order or enforce constraints.');

-- REORDER
INSERT INTO questions (language, difficulty, question_type, code_snippet, question_text, options, correct_answer, explanation) VALUES

-- ============ DIFFICULTY 1 (11 questions) ============

('python', 1, 'reorder',
 '',
 'Put these lines in order to define a function that returns the square of a number.',
 '["def square(n):", "    result = n * n", "    return result"]',
 '[0, 1, 2]',
 'First define the function signature, then compute the square and store it, then return the result.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to read a number from the user and print whether it is positive.',
 '["num = int(input(\"Enter a number: \"))", "if num > 0:", "    print(\"Positive\")"]',
 '[0, 1, 2]',
 'First read and convert the input, then check the condition, then print inside the if block.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to create a list of numbers and print its sum.',
 '["numbers = [1, 2, 3, 4, 5]", "total = sum(numbers)", "print(total)"]',
 '[0, 1, 2]',
 'First create the list, then compute the sum, then print the result.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to define a function that greets someone by name.',
 '["def greet(name):", "    message = \"Hello, \" + name + \"!\"", "    print(message)"]',
 '[0, 1, 2]',
 'First define the function, then build the greeting string, then print it.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to swap the values of two variables and print the result.',
 '["a = 10", "b = 20", "a, b = b, a", "print(a, b)"]',
 '[0, 1, 2, 3]',
 'First assign both variables, then swap them using tuple unpacking, then print.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to loop through a list and print each item uppercased.',
 '["words = [\"hello\", \"world\"]", "for word in words:", "    print(word.upper())"]',
 '[0, 1, 2]',
 'First define the list, then start the for loop, then print each word uppercased inside the loop body.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to define a function that checks if a number is even.',
 '["def is_even(n):", "    if n % 2 == 0:", "        return True", "    return False"]',
 '[0, 1, 2, 3]',
 'Define the function, check the modulo condition, return True inside the if, and return False as the fallback.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to build a string using an f-string and print it.',
 '["name = \"Alice\"", "age = 30", "info = f\"{name} is {age} years old\"", "print(info)"]',
 '[0, 1, 2, 3]',
 'First assign the variables, then build the f-string using them, then print.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to create a dictionary and access a value from it.',
 '["person = {\"name\": \"Bob\", \"age\": 25}", "name = person[\"name\"]", "print(name)"]',
 '[0, 1, 2]',
 'First create the dictionary, then look up the key, then print the value.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to use a while loop to count down from 3 to 1.',
 '["n = 3", "while n > 0:", "    print(n)", "    n -= 1"]',
 '[0, 1, 2, 3]',
 'Initialize the counter, start the while loop with the condition, print the current value, then decrement.'),

('python', 1, 'reorder',
 '',
 'Put these lines in order to define a function that returns the maximum of two numbers.',
 '["def maximum(a, b):", "    if a > b:", "        return a", "    return b"]',
 '[0, 1, 2, 3]',
 'Define the function, check if a is greater, return a if so, otherwise return b.'),

-- ============ DIFFICULTY 2 (11 questions) ============

('python', 2, 'reorder',
 '',
 'Put these lines in order to define a class with an __init__ method and a greet method.',
 '["class Person:", "    def __init__(self, name):", "        self.name = name", "    def greet(self):", "        print(f\"Hi, I''m {self.name}\")"]',
 '[0, 1, 2, 3, 4]',
 'Start with the class definition, then __init__ with its parameter and body, then the greet method with its body.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to safely convert a string to an integer using try/except.',
 '["def safe_int(s):", "    try:", "        return int(s)", "    except ValueError:", "        return None"]',
 '[0, 1, 2, 3, 4]',
 'Define the function, open the try block, attempt the conversion, catch ValueError, and return None on failure.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to read a file and print its contents.',
 '["f = open(\"data.txt\", \"r\")", "contents = f.read()", "print(contents)", "f.close()"]',
 '[0, 1, 2, 3]',
 'Open the file first, read its contents, print them, then close the file handle.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to create a list comprehension that filters even numbers and print it.',
 '["numbers = [1, 2, 3, 4, 5, 6]", "evens = [n for n in numbers if n % 2 == 0]", "print(evens)"]',
 '[0, 1, 2]',
 'First define the source list, then build the filtered list with a comprehension, then print the result.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to define a function with a default parameter and call it.',
 '["def power(base, exp=2):", "    return base ** exp", "result = power(3)", "print(result)"]',
 '[0, 1, 2, 3]',
 'Define the function with a default exponent of 2, write the return statement, call it with one argument, and print.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to use enumerate to print indices and values of a list.',
 '["fruits = [\"apple\", \"banana\", \"cherry\"]", "for i, fruit in enumerate(fruits):", "    print(f\"{i}: {fruit}\")"]',
 '[0, 1, 2]',
 'First create the list, then iterate with enumerate to get index and value, then print them formatted.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to define a class that inherits from a parent class.',
 '["class Animal:", "    def speak(self):", "        return \"...\"", "class Dog(Animal):", "    def speak(self):", "        return \"Woof!\""]',
 '[0, 1, 2, 3, 4, 5]',
 'First define the parent class with its method, then define the child class inheriting from it and overriding the method.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to sort a list of tuples by the second element.',
 '["pairs = [(1, \"b\"), (3, \"a\"), (2, \"c\")]", "pairs.sort(key=lambda x: x[1])", "print(pairs)"]',
 '[0, 1, 2]',
 'First define the list of tuples, then sort using a lambda that extracts the second element, then print.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to use a dictionary comprehension to create a squared-values dict.',
 '["numbers = [1, 2, 3, 4]", "squared = {n: n ** 2 for n in numbers}", "print(squared)"]',
 '[0, 1, 2]',
 'First define the source list, then build the dict comprehension mapping each number to its square, then print.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to use *args to define a function that sums all its arguments.',
 '["def add_all(*args):", "    total = sum(args)", "    return total", "print(add_all(1, 2, 3))"]',
 '[0, 1, 2, 3]',
 'Define the function with *args, sum the arguments, return the total, then call and print.'),

('python', 2, 'reorder',
 '',
 'Put these lines in order to write data to a file using a with statement.',
 '["data = \"Hello, file!\"", "with open(\"output.txt\", \"w\") as f:", "    f.write(data)", "print(\"Done writing\")"]',
 '[0, 1, 2, 3]',
 'First prepare the data string, open the file with a context manager, write the data, then print confirmation after the block.'),

-- ============ DIFFICULTY 3 (11 questions) ============

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a simple decorator that logs function calls.',
 '["def log_calls(func):", "    def wrapper(*args, **kwargs):", "        print(f\"Calling {func.__name__}\")", "        return func(*args, **kwargs)", "    return wrapper"]',
 '[0, 1, 2, 3, 4]',
 'Define the decorator function, define the inner wrapper, log the call, call the original function and return its result, then return the wrapper.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a generator function that yields Fibonacci numbers.',
 '["def fibonacci():", "    a, b = 0, 1", "    while True:", "        yield a", "        a, b = b, a + b"]',
 '[0, 1, 2, 3, 4]',
 'Define the generator, initialize the two starting values, loop forever, yield the current value, then update both values.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a context manager class for timing code.',
 '["import time", "class Timer:", "    def __enter__(self):", "        self.start = time.time()", "        return self", "    def __exit__(self, *args):", "        print(f\"Elapsed: {time.time() - self.start:.2f}s\")"]',
 '[0, 1, 2, 3, 4, 5, 6]',
 'Import time first, define the class, implement __enter__ to record start time and return self, then implement __exit__ to compute and print elapsed time.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a recursive function for computing factorial.',
 '["def factorial(n):", "    if n <= 1:", "        return 1", "    return n * factorial(n - 1)"]',
 '[0, 1, 2, 3]',
 'Define the function, check the base case, return 1 for the base case, then return the recursive multiplication.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to implement a property with a getter and setter.',
 '["class Circle:", "    def __init__(self, radius):", "        self._radius = radius", "    @property", "    def radius(self):", "        return self._radius", "    @radius.setter", "    def radius(self, value):", "        if value < 0:", "            raise ValueError(\"Radius must be non-negative\")", "        self._radius = value"]',
 '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
 'Define the class and __init__, then the @property getter, then the @radius.setter that validates before assigning.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to use functools.reduce to compute the product of a list.',
 '["from functools import reduce", "numbers = [1, 2, 3, 4, 5]", "product = reduce(lambda a, b: a * b, numbers)", "print(product)"]',
 '[0, 1, 2, 3]',
 'Import reduce first, define the list, apply reduce with a multiplication lambda, then print the product.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a decorator that caches function results.',
 '["def memoize(func):", "    cache = {}", "    def wrapper(*args):", "        if args not in cache:", "            cache[args] = func(*args)", "        return cache[args]", "    return wrapper"]',
 '[0, 1, 2, 3, 4, 5, 6]',
 'Define the decorator, initialize the cache dict, define the wrapper, check if args are cached, compute and store if not, return the cached value, then return the wrapper.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to implement __repr__ and __eq__ on a custom class.',
 '["class Point:", "    def __init__(self, x, y):", "        self.x, self.y = x, y", "    def __repr__(self):", "        return f\"Point({self.x}, {self.y})\"", "    def __eq__(self, other):", "        return self.x == other.x and self.y == other.y"]',
 '[0, 1, 2, 3, 4, 5, 6]',
 'Define the class and __init__ to store coordinates, then __repr__ for string representation, then __eq__ for equality comparison.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to create a named tuple and use it.',
 '["from collections import namedtuple", "Color = namedtuple(\"Color\", [\"red\", \"green\", \"blue\"])", "white = Color(255, 255, 255)", "print(white.red)"]',
 '[0, 1, 2, 3]',
 'Import namedtuple, define the Color type with field names, create an instance, then access a field.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a generator-based context manager using contextlib.',
 '["from contextlib import contextmanager", "@contextmanager", "def managed_resource():", "    print(\"Acquiring\")", "    yield \"resource\"", "    print(\"Releasing\")"]',
 '[0, 1, 2, 3, 4, 5]',
 'Import contextmanager, apply the decorator, define the generator function, print acquisition, yield the resource, then print release on cleanup.'),

('python', 3, 'reorder',
 '',
 'Put these lines in order to define a recursive binary search function.',
 '["def binary_search(arr, target, lo, hi):", "    if lo > hi:", "        return -1", "    mid = (lo + hi) // 2", "    if arr[mid] == target:", "        return mid", "    elif arr[mid] < target:", "        return binary_search(arr, target, mid + 1, hi)", "    else:", "        return binary_search(arr, target, lo, mid - 1)"]',
 '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]',
 'Define the function, check the base case for not found, compute midpoint, check if found, recurse right if too small, recurse left if too large.'),

-- ============ DIFFICULTY 4 (11 questions) ============

('python', 4, 'reorder',
 '',
 'Put these lines in order to define a metaclass that auto-registers subclasses.',
 '["class Registry(type):", "    _classes = {}", "    def __new__(mcs, name, bases, namespace):", "        cls = super().__new__(mcs, name, bases, namespace)", "        mcs._classes[name] = cls", "        return cls"]',
 '[0, 1, 2, 3, 4, 5]',
 'Define the metaclass inheriting from type, initialize the registry dict, override __new__, call super().__new__ to create the class, register it by name, then return it.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to define an async function that fetches multiple URLs concurrently.',
 '["import asyncio", "import aiohttp", "async def fetch_all(urls):", "    async with aiohttp.ClientSession() as session:", "        tasks = [session.get(url) for url in urls]", "        return await asyncio.gather(*tasks)"]',
 '[0, 1, 2, 3, 4, 5]',
 'Import asyncio and aiohttp, define the async function, open a client session, create a task list, then gather all tasks concurrently.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to implement the descriptor protocol for a validated attribute.',
 '["class Positive:", "    def __set_name__(self, owner, name):", "        self.name = name", "    def __get__(self, obj, objtype=None):", "        return getattr(obj, f\"_{self.name}\", None)", "    def __set__(self, obj, value):", "        if value < 0:", "            raise ValueError(\"Must be positive\")", "        setattr(obj, f\"_{self.name}\", value)"]',
 '[0, 1, 2, 3, 4, 5, 6, 7, 8]',
 'Define the descriptor class, implement __set_name__ to store the attribute name, __get__ to retrieve the private attribute, and __set__ to validate and store the value.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to define an async generator that yields items with a delay.',
 '["import asyncio", "async def timed_counter(n, delay):", "    for i in range(n):", "        await asyncio.sleep(delay)", "        yield i"]',
 '[0, 1, 2, 3, 4]',
 'Import asyncio, define the async generator, loop through range, await the delay, then yield the current value.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to create a class using __init_subclass__ to enforce an interface.',
 '["class Plugin:", "    def __init_subclass__(cls, **kwargs):", "        super().__init_subclass__(**kwargs)", "        if not hasattr(cls, \"execute\"):", "            raise TypeError(f\"{cls.__name__} must define execute()\")"]',
 '[0, 1, 2, 3, 4]',
 'Define the base class, override __init_subclass__, call super, check for the required method, raise TypeError if missing.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to implement __class_getitem__ for a generic-style container.',
 '["class TypedBox:", "    def __init__(self, value):", "        self.value = value", "    def __class_getitem__(cls, item):", "        return type(f\"TypedBox[{item.__name__}]\", (cls,), {\"_type\": item})"]',
 '[0, 1, 2, 3, 4]',
 'Define the class, implement __init__ to store the value, then implement __class_getitem__ to dynamically create a specialized subclass.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to define an async context manager class.',
 '["class AsyncDB:", "    async def __aenter__(self):", "        self.conn = await self._connect()", "        return self", "    async def __aexit__(self, exc_type, exc_val, exc_tb):", "        await self.conn.close()", "        return False"]',
 '[0, 1, 2, 3, 4, 5, 6]',
 'Define the class, implement __aenter__ to establish and return the connection, then __aexit__ to close it and not suppress exceptions.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to implement a decorator that preserves the original function''s signature.',
 '["import functools", "def retry(max_attempts=3):", "    def decorator(func):", "        @functools.wraps(func)", "        def wrapper(*args, **kwargs):", "            for attempt in range(max_attempts):", "                try:", "                    return func(*args, **kwargs)", "                except Exception:", "                    if attempt == max_attempts - 1:", "                        raise"]',
 '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
 'Import functools, define the parameterized decorator, define the inner decorator, apply wraps, define the wrapper, loop attempts, try calling, return on success, catch exceptions, and re-raise on final attempt.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to define a dataclass with a post-init validator and a computed field.',
 '["from dataclasses import dataclass, field", "@dataclass", "class Temperature:", "    celsius: float", "    fahrenheit: float = field(init=False)", "    def __post_init__(self):", "        if self.celsius < -273.15:", "            raise ValueError(\"Below absolute zero\")", "        self.fahrenheit = self.celsius * 9/5 + 32"]',
 '[0, 1, 2, 3, 4, 5, 6, 7, 8]',
 'Import dataclass utilities, apply the decorator, define the class with celsius field, declare fahrenheit as a non-init field, then validate in __post_init__ and compute fahrenheit.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to create an abstract base class with an abstract method and a concrete method.',
 '["from abc import ABC, abstractmethod", "class Shape(ABC):", "    @abstractmethod", "    def area(self):", "        pass", "    def describe(self):", "        return f\"Shape with area {self.area():.2f}\""]',
 '[0, 1, 2, 3, 4, 5, 6]',
 'Import ABC and abstractmethod, define the abstract class, declare the abstract area method, then define the concrete describe method that calls area.'),

('python', 4, 'reorder',
 '',
 'Put these lines in order to implement __slots__ with a class hierarchy for memory optimization.',
 '["class Base:", "    __slots__ = (\"x\", \"y\")", "    def __init__(self, x, y):", "        self.x, self.y = x, y", "class Extended(Base):", "    __slots__ = (\"z\",)", "    def __init__(self, x, y, z):", "        super().__init__(x, y)", "        self.z = z"]',
 '[0, 1, 2, 3, 4, 5, 6, 7, 8]',
 'Define the base class with __slots__ for x and y, implement its __init__, then define the child class adding slot z, calling super().__init__, and setting z.');

-- FILL IN THE BLANK
INSERT INTO questions (language, difficulty, question_type, code_snippet, question_text, options, correct_answer, explanation) VALUES

-- DIFFICULTY 1 (11 questions)

('python', 1, 'fill_blank',
 '___ greet(name):\n    ___ "Hello, " + name',
 'Fill in the blanks to define a function that returns a greeting.',
 '["def", "return", "func", "print"]',
 '[0, 1]',
 '"def" defines a function and "return" sends back the result to the caller.'),

('python', 1, 'fill_blank',
 'x = 10\nif x ___ 5:\n    print(___)',
 'Fill in the blanks to print "big" when x is greater than 5.',
 '[">", "\"big\"", "<", "\"small\""]',
 '[0, 1]',
 'The > operator checks if x is greater than 5, and "big" is the string to print.'),

('python', 1, 'fill_blank',
 'fruits = ["apple", "banana"]\nfruits.___("cherry")\nprint(___(fruits))',
 'Fill in the blanks to add "cherry" to the list and print its length.',
 '["append", "len", "add", "size"]',
 '[0, 1]',
 'The append() method adds an item to a list, and len() returns the number of items.'),

('python', 1, 'fill_blank',
 'i = 0\n___ i < 3:\n    print(i)\n    i ___ 1',
 'Fill in the blanks to print 0, 1, 2 using a while loop.',
 '["while", "+= ", "for", "= "]',
 '[0, 1]',
 '"while" creates the loop and "+= 1" increments i by 1 each iteration.'),

('python', 1, 'fill_blank',
 'age = 15\nstatus = "adult" ___ age >= 18 ___ "minor"',
 'Fill in the blanks to assign "adult" or "minor" using a ternary expression.',
 '["if", "else", "when", "then"]',
 '[0, 1]',
 'Python''s ternary syntax is: value_if_true if condition else value_if_false.'),

('python', 1, 'fill_blank',
 'numbers = [1, 2, 3, 4]\ntotal = ___(numbers)\navg = total / ___(numbers)',
 'Fill in the blanks to calculate the average of the list.',
 '["sum", "len", "add", "count"]',
 '[0, 1]',
 'sum() adds all elements and len() returns the count, giving the average.'),

('python', 1, 'fill_blank',
 'text = "hello world"\nprint(text.___())\nprint(text.___())',
 'Fill in the blanks to print the text in uppercase, then in title case.',
 '["upper", "title", "capitalize", "lower"]',
 '[0, 1]',
 'upper() converts to all uppercase and title() capitalizes the first letter of each word.'),

('python', 1, 'fill_blank',
 'for i in range(1, 11):\n    if i % 2 ___ 0:\n        ___',
 'Fill in the blanks to skip even numbers in the loop.',
 '["==", "continue", "!=", "break"]',
 '[0, 1]',
 'i % 2 == 0 checks if the number is even, and continue skips to the next iteration.'),

('python', 1, 'fill_blank',
 'person = {}\nperson[___] = "Alice"\nprint(person.get("name", ___))',
 'Fill in the blanks to set the name key and provide a default value.',
 '["\"name\"", "\"Unknown\"", "\"key\"", "None"]',
 '[0, 1]',
 '"name" is the dictionary key, and "Unknown" is the default if the key is missing.'),

('python', 1, 'fill_blank',
 'try:\n    result = 10 / 0\n___ ZeroDivisionError:\n    result = ___',
 'Fill in the blanks to handle a division by zero error and set result to 0.',
 '["except", "0", "catch", "-1"]',
 '[0, 1]',
 '"except" catches the exception, and 0 is a sensible default for failed division.'),

('python', 1, 'fill_blank',
 'a = 5\nb = 3\na, b = ___, ___\nprint(a, b)',
 'Fill in the blanks to swap the values of a and b.',
 '["b", "a", "5", "3"]',
 '[0, 1]',
 'Python allows tuple unpacking to swap: a, b = b, a gives a=3 and b=5.'),

-- DIFFICULTY 2 (11 questions)

('python', 2, 'fill_blank',
 'squares = [x ** 2 ___ x in range(10) ___ x % 2 == 0]',
 'Fill in the blanks to create a list of squares of even numbers from 0-9.',
 '["for", "if", "while", "and"]',
 '[0, 1]',
 '"for" iterates over the range and "if" filters to include only even numbers.'),

('python', 2, 'fill_blank',
 'name = "Alice"\nage = 30\nprint(f"___ is {___} years old")',
 'Fill in the blanks to use an f-string that prints "Alice is 30 years old".',
 '["{ name }", "age", "name", "{ age }"]',
 '[0, 1]',
 'In f-strings, {name} inserts the variable name, and age inside {} inserts 30.'),

('python', 2, 'fill_blank',
 'data = {"a": 1, "b": 2, "c": 3}\nkeys = list(data.___())\nvals = list(data.___())',
 'Fill in the blanks to get all keys and values from the dictionary.',
 '["keys", "values", "items", "pairs"]',
 '[0, 1]',
 'keys() returns dictionary keys and values() returns dictionary values.'),

('python', 2, 'fill_blank',
 'text = "hello world"\nwords = text.___(" ")\nresult = "-".___( words)',
 'Fill in the blanks to split by spaces and rejoin with hyphens.',
 '["split", "join", "divide", "concat"]',
 '[0, 1]',
 'split(" ") breaks the string into a list, and "-".join() reassembles with hyphens.'),

('python', 2, 'fill_blank',
 'matrix = [[1, 2], [3, 4], [5, 6]]\nflat = [num for ___ in matrix for num in ___]',
 'Fill in the blanks to flatten a 2D list into a 1D list.',
 '["row", "row", "col", "matrix"]',
 '[0, 1]',
 'The outer loop iterates rows and the inner loop iterates each num in that row.'),

('python', 2, 'fill_blank',
 'nums = [3, 1, 4, 1, 5]\nnums.sort(___=True)\nprint(nums[___])',
 'Fill in the blanks to sort in descending order and print the smallest element.',
 '["reverse", "-1", "descending", "0"]',
 '[0, 1]',
 'reverse=True sorts descending, so the last element (index -1) is the smallest.'),

('python', 2, 'fill_blank',
 'a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\ncommon = a.___(b)\nall_items = a.___(b)',
 'Fill in the blanks to find common elements and all unique elements of two sets.',
 '["intersection", "union", "difference", "symmetric_difference"]',
 '[0, 1]',
 'intersection() finds shared elements and union() combines all unique elements.'),

('python', 2, 'fill_blank',
 'text = "  Hello, World!  "\nclean = text.___().___(\"!\")',
 'Fill in the blanks to remove whitespace and then remove the exclamation mark.',
 '["strip", "rstrip", "trim", "replace"]',
 '[0, 1]',
 'strip() removes leading/trailing whitespace and rstrip("!") removes trailing "!".'),

('python', 2, 'fill_blank',
 'counts = {}\nfor ch in "abracadabra":\n    counts[ch] = counts.___(ch, 0) ___ 1',
 'Fill in the blanks to count character frequencies in a string.',
 '["get", "+", "find", "* "]',
 '[0, 1]',
 'get(ch, 0) returns 0 if the key is missing, and + 1 increments the count.'),

('python', 2, 'fill_blank',
 'import os\npath = os.path.___("home", "user", "file.txt")\nexists = os.path.___(path)',
 'Fill in the blanks to join path components and check if the file exists.',
 '["join", "exists", "combine", "isfile"]',
 '[0, 1]',
 'os.path.join() builds a path string and os.path.exists() checks if it exists.'),

('python', 2, 'fill_blank',
 'numbers = [1, 2, 3, 4, 5]\nfirst_three = numbers[:___]\nlast_two = numbers[-___:]',
 'Fill in the blanks to slice the first 3 and last 2 elements.',
 '["3", "2", "4", "1"]',
 '[0, 1]',
 '[:3] takes elements at indices 0-2, and [-2:] takes the last two elements.'),

-- DIFFICULTY 3 (12 questions)

('python', 3, 'fill_blank',
 'double = ___ x: x ___ 2\nprint(double(5))',
 'Fill in the blanks to create a lambda that doubles a number.',
 '["lambda", "*", "def", "+"]',
 '[0, 1]',
 '"lambda" creates an anonymous function and * 2 doubles the input value.'),

('python', 3, 'fill_blank',
 'nums = [1, 2, 3, 4, 5, 6]\nevens = list(___(___ x: x % 2 == 0, nums))',
 'Fill in the blanks to filter even numbers using filter and lambda.',
 '["filter", "lambda", "map", "def"]',
 '[0, 1]',
 'filter() selects elements matching a condition, and lambda defines the inline test.'),

('python', 3, 'fill_blank',
 'def decorator(func):\n    def ___(*args, **kwargs):\n        print("Before")\n        result = ___(* args, **kwargs)\n        print("After")\n        return result\n    return wrapper',
 'Fill in the blanks to complete this decorator function.',
 '["wrapper", "func", "inner", "self"]',
 '[0, 1]',
 'The inner function is named "wrapper" and it calls the original "func" inside.'),

('python', 3, 'fill_blank',
 'with ___("data.txt", "r") as ___:\n    content = f.read()',
 'Fill in the blanks to open a file using a context manager.',
 '["open", "f", "file", "fp"]',
 '[0, 1]',
 'open() returns a file object, and "as f" binds it to a variable for use inside the block.'),

('python', 3, 'fill_blank',
 'def fibonacci():\n    a, b = 0, 1\n    while True:\n        ___ a\n        a, b = b, ___',
 'Fill in the blanks to create a Fibonacci generator.',
 '["yield", "a + b", "return", "a * b"]',
 '[0, 1]',
 '"yield" makes this a generator, and a + b computes the next Fibonacci number.'),

('python', 3, 'fill_blank',
 'first, *___, last = [1, 2, 3, 4, 5]\nprint(___)',
 'Fill in the blanks to unpack the first, middle, and last elements.',
 '["middle", "middle", "rest", "args"]',
 '[0, 1]',
 '*middle captures all elements between first and last, then print(middle) shows [2, 3, 4].'),

('python', 3, 'fill_blank',
 'from functools import ___\n\n@___(maxsize=128)\ndef fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)',
 'Fill in the blanks to add memoization to the Fibonacci function.',
 '["lru_cache", "lru_cache", "cache", "memoize"]',
 '[0, 1]',
 'lru_cache is imported from functools and used as a decorator to cache results.'),

('python', 3, 'fill_blank',
 'data = {"name": "Alice", "age": 30, "city": "NYC"}\nresult = {k: v for k, v in data.___() if ___(v) == str}',
 'Fill in the blanks to create a dict with only string-valued entries.',
 '["items", "type", "values", "isinstance"]',
 '[0, 1]',
 'items() gives key-value pairs and type(v) == str checks if the value is a string.'),

('python', 3, 'fill_blank',
 'import re\ntext = "Call 123-456-7890 or 987-654-3210"\nphones = re.___(r"\\d{3}-\\d{3}-\\d{4}", ___)',
 'Fill in the blanks to find all phone numbers in the text.',
 '["findall", "text", "match", "phones"]',
 '[0, 1]',
 're.findall() returns all matches of the pattern, and text is the string to search.'),

('python', 3, 'fill_blank',
 'from collections import ___\nwords = ["apple", "banana", "apple", "cherry", "banana", "apple"]\ncounts = ___(words)',
 'Fill in the blanks to count word frequencies using collections.',
 '["Counter", "Counter", "defaultdict", "OrderedDict"]',
 '[0, 1]',
 'Counter is imported from collections and Counter(words) counts each element.'),

('python', 3, 'fill_blank',
 'nums = [1, 2, 3]\nstrs = ["a", "b", "c"]\npairs = list(___(nums, strs))\nprint(dict(___))',
 'Fill in the blanks to zip two lists and convert them to a dictionary.',
 '["zip", "pairs", "map", "enumerate"]',
 '[0, 1]',
 'zip() pairs elements from both lists and dict(pairs) creates a dictionary from them.'),

('python', 3, 'fill_blank',
 'from contextlib import ___\n\n@___\ndef managed_resource():\n    print("Setup")\n    yield\n    print("Teardown")',
 'Fill in the blanks to create a context manager using a decorator.',
 '["contextmanager", "contextmanager", "contextlib", "generator"]',
 '[0, 1]',
 'contextmanager is imported from contextlib and used as a decorator on a generator function.'),

-- DIFFICULTY 4 (11 questions)

('python', 4, 'fill_blank',
 'class Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def ___(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n    def ___(self):\n        return f"Vector({self.x}, {self.y})"',
 'Fill in the blanks to support + operator and string representation.',
 '["__add__", "__repr__", "__sum__", "__str__"]',
 '[0, 1]',
 '__add__ enables the + operator and __repr__ provides the string representation.'),

('python', 4, 'fill_blank',
 'class MyCtx:\n    def ___(self):\n        print("entering")\n        return self\n    def ___(self, exc_type, exc_val, exc_tb):\n        print("exiting")\n        return False',
 'Fill in the blanks to make this class usable as a context manager.',
 '["__enter__", "__exit__", "__start__", "__stop__"]',
 '[0, 1]',
 '__enter__ is called when entering a with block, __exit__ is called when leaving it.'),

('python', 4, 'fill_blank',
 'import asyncio\n\nasync def fetch_data():\n    ___ asyncio.sleep(1)\n    return "data"\n\nresult = asyncio.___(fetch_data())',
 'Fill in the blanks to create and run an async function.',
 '["await", "run", "yield", "execute"]',
 '[0, 1]',
 '"await" pauses until the coroutine completes and asyncio.run() executes the event loop.'),

('python', 4, 'fill_blank',
 'class Celsius:\n    def __init__(self):\n        self._temp = 0\n    @___\n    def temperature(self):\n        return self._temp\n    @temperature.___\n    def temperature(self, value):\n        if value < -273.15:\n            raise ValueError("Too cold")\n        self._temp = value',
 'Fill in the blanks to create a property with validation.',
 '["property", "setter", "staticmethod", "getter"]',
 '[0, 1]',
 '@property creates a getter and @temperature.setter defines the setter with validation.'),

('python', 4, 'fill_blank',
 'class Meta(type):\n    def ___(___, name, bases, namespace):\n        namespace["created_by"] = "Meta"\n        return ___().__new__(cls, name, bases, namespace)',
 'Fill in the blanks to create a metaclass that adds an attribute.',
 '["__new__", "super", "__init__", "cls"]',
 '[0, 1]',
 '__new__ controls class creation in metaclasses, and super() calls the parent type.__new__.'),

('python', 4, 'fill_blank',
 'class Immutable:\n    def __init__(self, value):\n        object.___( self, "_value", value)\n    def ___( self, name, value):\n        raise AttributeError("Cannot modify")',
 'Fill in the blanks to create an immutable class that prevents attribute changes.',
 '["__setattr__", "__setattr__", "__setitem__", "__delattr__"]',
 '[0, 1]',
 'object.__setattr__ bypasses the override in __init__, and __setattr__ blocks all other modifications.'),

('python', 4, 'fill_blank',
 'class LazyProperty:\n    def __init__(self, func):\n        self.func = func\n    def ___(self, obj, objtype=None):\n        if obj is None:\n            return self\n        value = self.func(obj)\n        ___(obj, self.func.__name__, value)\n        return value',
 'Fill in the blanks to create a lazy-loading descriptor.',
 '["__get__", "setattr", "__set__", "getattr"]',
 '[0, 1]',
 '__get__ is the descriptor protocol method and setattr caches the result on the instance.'),

('python', 4, 'fill_blank',
 'from typing import ___\n\ndef process(items: List[int]) -> ___[str, int]:\n    return ", ".join(map(str, items)), len(items)',
 'Fill in the blanks to add type hints for a function returning a tuple.',
 '["List", "Tuple", "Set", "Dict"]',
 '[0, 1]',
 'List is used for the parameter type and Tuple for the return type of (str, int).'),

('python', 4, 'fill_blank',
 'class Singleton:\n    _instance = None\n    def __new__(___, *args, **kwargs):\n        if cls._instance is ___:\n            cls._instance = super().__new__(cls)\n        return cls._instance',
 'Fill in the blanks to implement the Singleton pattern.',
 '["cls", "None", "self", "True"]',
 '[0, 1]',
 '"cls" is the first parameter of __new__ and "None" checks if an instance exists yet.'),

('python', 4, 'fill_blank',
 'class Account:\n    def __init__(self, balance):\n        self.balance = balance\n    def __lt__(self, other):\n        return self.balance ___ other.balance\n    def __eq__(self, other):\n        return self.balance ___ other.balance',
 'Fill in the blanks to enable comparison operators between Account objects.',
 '["<", "==", ">", "!="]',
 '[0, 1]',
 '__lt__ uses < to compare balances and __eq__ uses == to check equality.'),

('python', 4, 'fill_blank',
 'import ___\n\ndef add(a: int, b: int) -> int:\n    return a + b\n\nsig = ___.signature(add)\nprint(sig.parameters)',
 'Fill in the blanks to introspect a function''s signature.',
 '["inspect", "inspect", "functools", "types"]',
 '[0, 1]',
 'The inspect module is imported and inspect.signature() retrieves the function''s parameter info.');
